name: 'dbt_showcase'
version: '1.0.0'
config-version: 2

profile: 'dbt_showcase'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_showcase:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: ephemeral

    marts:
      +materialized: table
      core:
        +schema: core
      analytics:
        +schema: analytics

vars:
  start_date: '2017-01-01'
